#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed May 13 19:04:58 BST 2026
# SW Build 6233196 on Thu Sep 11 21:27:11 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim spi_top_hw_behav -key {Behavioral:sim_1:Functional:spi_top_hw} -tclbatch spi_top_hw.tcl -log simulate.log"
xsim spi_top_hw_behav -key {Behavioral:sim_1:Functional:spi_top_hw} -tclbatch spi_top_hw.tcl -log simulate.log

