/* verilator lint_off DECLFILENAME */
module spi_master
  /* verilator lint_off UNUSEDPARAM */
  #(parameter spi_mode = 0,
    /* verilator lint_on UNUSEDPARAM */
    parameter clks_per_half_bit = 2)

  (
   // General architecture
   // Master ---> Slave
   //   CS ------> CS
   //   SCLK ----> SCLK
   //   MOSI ----> MOSI
   //   MISO <---- MISO

   // Inner workings
   // Chip Select (CS)
   // 0. Master CS is pulled low (low voltage, 0V, from 1->0).
   // 1. Master CS establishes a connection with the slave CS for communication.
   // 2. Slave CS listens for the master SLCK and MOSI.
   // 3. CS returns to a high state (high voltage, 0->1).

   // Signal Clock (SCLK)
   // - SCLK can be either active high, idle low or idle high, active low.
   // - Always generated by the master.
   // - SLCK indicates when to read data (voltage levels, like a traffic light).

   // Master Out, Slave In (MOSI)
   // - Sends data, as bytes, from master to slave(s).
   // - Multiple bytes can be sent sequentially, for the duration of CS low.

   // Master in, Slave Out (MISO)
   // - Sends data from slave(s) to master.
   // - For this to work, the master must know how many clock cycles (SCLK) to
   // generate so the slave can send all its data.
   // - May be known in advance or the slave may be queried for the information.

   // Clock Polarity (CPOL)
   // - SCLK can be either:

   // Active high     ┌─┐ ┌─┐ ┌─┐ ┌─┐ ┌─┐ CPOL = 0 (non-inverted/ active high)
   // Idle low    ____│ │_│ │_│ │_│ │_│ │
   //               or
   // Idle high    ---┐ ┌─┐ ┌─┐ ┌─┐ ┌─┐ ┌─-----
   // Active low      │_│ │_│ │_│ │_│ │_│       CPOL = 1 (inverted/ active low)

   // - CPOL's "job" is to indicate which of the above SCLK states is being used.
   // - the ↑ rising | is the leading (first) edge.
   // - the ↓ falling | is the trailing (second) edge.

   // Clock Phase (CPHA)
   // - CPHA's job is to decide which clock edge TO use, FOR the above CPOL states.
   // - CPHA 0: Data sampled on the LEADING edge (1st edge after CS goes low).
   // - CPHA 1: Data sampled on the TRAILING edge (2nd edge).
   // - Which physical edge (↑ or ↓) is "leading" depends on CPOL.

   // User-facing
   input [7:0]        i_tx_byte,  // send byte
   input              i_tx_dv,    // *action* Fire! -> load action onto and transfer via mosi
   output logic       o_tx_ready, // ready for 2nd wave (sclk)
   output logic [7:0] o_rx_byte,  // receive loot from miso
   output logic       o_rx_dv,

   // SPI-facing
   output logic       o_cs_n,
   output logic       o_sclk,
   output logic       o_mosi,
   input              i_miso,

   // General
   input              i_clk,
   input              i_rst_l
   );

  // The module need to track:
  // 1. Clock generation - how do I divide the system clock down to sclk?
  // 2. Edge detection - how does logic know when a trailing/leading edge has
  // occured
  // 3. Bit counting - how does it know which of the 8 bits it's currently
  // sending/receiving?
  // 4. Data rgisters - where does it hold the TX byte while shifting it out, and
  // accumulate the RX byte shifting in?

  reg [7:0]    r_clk_count;        // clock counter
  reg          r_trailing;         // trailing edge flag
  reg          r_leading;          // leading edge flag
  reg [2:0]    r_bit_count;        // bit counter
  /* verilator lint_off UNUSEDSIGNAL */
  reg [7:0]    r_tx_byte;          // tx shift register
  /* verilator lint_on UNUSEDSIGNAL */
  reg [7:0]    r_rx_byte;          // rx shift register

  // Block 1: sclk generator
  always_ff @(posedge i_clk or negedge i_rst_l) begin
    if (!i_rst_l)
      begin // reset everything to 0
        r_leading <= 1'b0;
        r_trailing <= 1'b0;
        r_clk_count <= 8'b0;
        o_sclk <= 1'b0; // CPOL begins at 0
      end
    else
      if (o_cs_n == 1'b0) // if cs is pulsing at 0
        begin
          if (r_clk_count == clks_per_half_bit - 1)
            begin
              r_clk_count <= 8'b0; // reset the counter to 0 (channelled)
              o_sclk      <= ~o_sclk; // immediately invert the voltage (0 to 1)

              // implementing the leading edge
              case (o_sclk)
                1'b0 :
                  begin
                    r_leading <= 1'b1;
                    r_trailing <= 1'b0;
                  end
                1'b1 :
                  begin
                    r_leading <= 1'b0;
                    r_trailing <= 1'b1;
                  end
              endcase
            end // if (r_clk_count == clks_per_half_bit - 1)
          else
            begin
              r_clk_count <= r_clk_count + 1'b1;
              r_leading <= 1'b0;
              r_trailing <= 1'b0;
            end
        end // if (o_cs_n == 1'b0)
      else
        begin
          r_leading <= 1'b0;
          r_trailing <= 1'b0;
        end
  end // always_ff @ (posedge i_clk or negedge i_rst_l)

  // Block 2: TX path (shift register)
  // Start (i_tx_dv): load the 8-bit byte into the register. Bit 7 first.
  // Reload (r_trailing): shift everything one slot to the left.
  // Output (o_mosi): permanently wire the bit 7 slot to the exit.
  always_ff @(posedge i_clk or negedge i_rst_l)
    if (!i_rst_l)
      begin
        r_tx_byte <= 8'b0;
        o_tx_ready <= 1'b1;
        o_mosi <= 1'b0;
      end
    else
      begin
        if (i_tx_dv && o_tx_ready)
          begin
            r_tx_byte <= i_tx_byte; // add the input to the inventory
            o_mosi <= i_tx_byte[7]; // begin at bit 7 immediately
            o_tx_ready <= 1'b0; // become busy
          end
        if (r_trailing == 1'b1)
          begin // as bit 7 has been used, begin cycling down the chamber
            r_tx_byte <= {r_tx_byte[6:0], 1'b0};
            o_mosi <= r_tx_byte[6];
            if (r_bit_count == 0 && !o_tx_ready)
              o_tx_ready <= 1'b1;
          end
      end // else: !if(!i_rst_l)

  // Block 3: MISO sampling
  // Captures i_miso into r_rx_byte, increments r_bit_count
  always_ff @(posedge i_clk or negedge i_rst_l)
    if (!i_rst_l)
      begin
        r_rx_byte <= 8'b0;
        r_bit_count <= 3'b0;
        o_rx_dv <= 1'b0;
      end
    else
      begin
        if (r_leading == 1'b1)
          begin
          r_rx_byte <= {i_miso, r_rx_byte[7:1]};
          r_bit_count <= r_bit_count + 1'b1;
          end
        if (r_bit_count == 7)
          o_rx_dv <= 1'b1;
        else
          o_rx_dv <= 1'b0;
      end // else: !if(!i_rst_l)
  assign o_cs_n = o_tx_ready;
  assign o_rx_byte = r_rx_byte;

`ifdef FORMAL
  assert property (@(posedge i_clk) !o_cs_n |-> !o_tx_ready);
  assert property (@(posedge i_clk) o_tx_ready |-> !o_mosi);
`endif
endmodule
